###############序列比对使用的工具#############
#blast必须使用，选择是否使用HMM进行进一步的筛选(默认使用)
#diamond: "yes" # ["yes"|| "NO"]
hmmsearch: "NO" # ["yes" || "NO"]
pfam: "yes" # ["yes" || "NO"]
clustal: "NO" # ["yes" || "NO"]

################ bin ########################
#blastp
blastp_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/miniconda/envs/blast/bin/blastp"
#blastx
blastx_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/miniconda/envs/blast/bin/blastx"
#diamond_blastp_path
diamond_blastp_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/miniconda/envs/blast/bin/diamond"
#diamond_blastx_path
diamond_blastx_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/miniconda/envs/blast/bin/diamond"
#clustalo
clustalo_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/miniconda/bin/clustalo"
#hmmsearch
hmmsearch_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/software/hmmsearch"
#hmmscan
hmmscan_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/software/hmmscan"
#hmmbuild
hmmbuild: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/software/hmmbuild"
#pfam
pfam_scan: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/software/pfam_scan.py"

################ 数据库位置 ##################
# 蛋白质blast目录
db_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/db/medusa-2023/all-hum-medusa-db-genmoic-protein-normalizename"
diamond_db_path: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/db/medusa-2023/all-hum-medusa-db-genmoic-protein-normalizename.dmnd"
# GCF目录位置
GCF_directory: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/db/medusa-taxon-genmoic/hum-medusa-db-all"
# pfam目录位置
pfam_dirextory: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/db/pfamdb"

################ 序列比对参数阈值设置 #########(默认是这个，可以在脚本中指定)
# blast
coverage_threshold: 0.7
identity_threshold: 30
# hmmsear
hmm_evalue : 0.0001
hmm_score : 0

################ GCF的物种注释信息 ############
GCF_annotation: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/db/medusa-2023//all-hum-medusa-db-GCF-name.txt"
medusa-annotation: "/cpfs01/projects-HDD/cfff-47998b01bebd_HDD/zzd_21250700018/db/medusa-2023/medus-annotation.Latest.txt"

